@startuml
skinparam backgroundColor white

title Product Change Flow Class Diagram

class ProductChangeListener{
validatorEngine: ValidatorEngine
markerViewConverter: MarketViewConverter
marketProcessor: MarketProcessor
}

interface MarketViewUpdateListener{
onMarketViewUpdates()
}

interface MarketProcessorPort{
}

MarketViewUpdateListener <|.. ProductChangeListener
ValidatorEngine <--o ProductChangeListener
MarketViewConverter <--o ProductChangeListener
MarketProcessorPort <--o ProductChangeListener
Teste <--o Teste


@enduml